# -*- coding: utf-8 -*-
"""desenhando-emojis-com-dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyC2srnoQLOv8oibuk4C8cgRIwgUrWWR
"""

emoji_data = {

  "nome": "Smile",

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]

  ]

}



AMARELO = (255, 255, 0)

PRETO = (0, 0, 0)



# 1º nível de loop: percorre as chaves e valores do dicionário

for chave, valor in emoji_data.items():



  # só nos interessa a grade (a lista de listas)

  if chave == "grade":



    nova_grade = [] # vai guardar as linhas com pixels já processados



    # 2º nível de loop: percorre cada linha da grade

    for linha in valor:



      nova_linha = [] # linha reconstruída com os pixels novos



      # 3º nível de loop: percorre cada pixel (tupla) da linha

      for pixel in linha:



        if pixel == AMARELO:

          # tupla imutável → cria uma nova dividindo cada canal por 2

          pixel_com_sombra = (pixel[0] // 2, pixel[1] // 2, pixel[2] // 2)

          nova_linha.append(pixel_com_sombra)

        else:

          # pixel preto não muda, só copia

          nova_linha.append(pixel)



      nova_grade.append(nova_linha) # adiciona a linha processada



    # atualiza o dicionário com a grade nova (com sombra aplicada)

    emoji_data["grade"] = nova_grade



# exibindo o resultado

print(f"Emoji: {emoji_data['nome']}")

print("Grade com filtro de sombra:")

for linha in emoji_data["grade"]:

  print(linha)

  biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}



# 1º nível de loop: percorre as chaves do dicionário principal

for chave_principal in biblioteca_musical:



  # 2º nível de loop: percorre cada item da lista de toques

  for toque in biblioteca_musical[chave_principal]:



    # cada 'toque' é um dict com uma única entrada ex: {"Alegre": ([...], [...])}

    for nome_musica, matriz in toque.items():



      # matriz é uma tupla de duas listas: ([linha0], [linha1])

      # transposta 2x2: nova_linha0 = [mat[0][0], mat[1][0]]

      #         nova_linha1 = [mat[0][1], mat[1][1]]



      transposta = []



      # 3º nível de loop: itera pelas colunas (índices 0 e 1)

      for col in range(len(matriz[0])):

        nova_linha = []

        for linha in matriz:     # percorre cada linha da matriz original

          nova_linha.append(linha[col])

        transposta.append(nova_linha)



      # .update() atualiza o dicionário do toque com a matriz transposta

      toque.update({nome_musica: transposta})



# exibindo o resultado

print("Matrizes transpostas:")

for toque in biblioteca_musical["Toques"]:

  for nome, matriz in toque.items():

    print(f" {nome}: {matriz}")

    # estrutura: dicionário principal contendo uma lista de frames (cenas)

# cada frame tem: nome (str), filtro (tupla com fator RGB), e grade (lista de listas de tuplas)



playlist_de_imagens = {

  "titulo": "Mini Animação Emoji",

  "frames": [

    {

      "cena": "Feliz",

      "filtro": (1.0, 1.0, 0.5),     # tupla: fatores R, G, B

      "grade": [

        [(255,255,0), (0,0,0), (255,255,0)],

        [(0,0,0),  (0,0,0), (0,0,0) ],

        [(255,255,0), (0,0,0), (255,255,0)]

      ]

    },

    {

      "cena": "Neutro",

      "filtro": (0.5, 0.5, 0.5),

      "grade": [

        [(255,255,0), (0,0,0), (255,255,0)],

        [(255,255,0), (255,255,0), (255,255,0)],

        [(255,255,0), (0,0,0), (255,255,0)]

      ]

    }

  ]

}



# insere um frame extra no início da playlist com .insert()

playlist_de_imagens["frames"].insert(0, {

  "cena": "Introdução",

  "filtro": (0.8, 0.8, 0.8),

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0)]

  ]

})



print(f"=== {playlist_de_imagens['titulo']} ===\n")



# 1º nível de loop: percorre as chaves do dicionário principal

for chave in playlist_de_imagens.keys(): # usando .keys()



  if chave != "frames":

    continue # pula a chave 'titulo', só nos interessa 'frames'



  # 2º nível de loop: percorre cada frame da lista

  for frame in playlist_de_imagens[chave]:



    cena = frame["cena"]

    filtro = frame["filtro"] # tupla (fR, fG, fB)

    grade = frame["grade"]



    print(f"--- Cena: {cena} | Filtro RGB: {filtro} ---")



    grade_filtrada = []



    # 3º nível de loop: percorre cada linha da grade

    for linha in grade:

      nova_linha = []



      for pixel in linha:

        # aplica o filtro da tupla em cada canal do pixel

        novo_pixel = (

          int(pixel[0] * filtro[0]),

          int(pixel[1] * filtro[1]),

          int(pixel[2] * filtro[2])

        )

        nova_linha.append(novo_pixel)

      grade_filtrada.append(nova_linha)



    # substitui a grade original pela filtrada no frame

    frame["grade"] = grade_filtrada



    for linha in frame["grade"]:

      print(" ", linha)

    print()



# remove o último frame com .pop() e informa qual foi removido

frame_removido = playlist_de_imagens["frames"].pop()

print(f"Frame removido ao final: '{frame_removido['cena']}'")

print(f"Frames restantes na playlist: {len(playlist_de_imagens['frames'])}")