# -*- coding: utf-8 -*-
"""SISTEMA_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyC2srnoQLOv8oibuk4C8cgRIwgUrWWR
"""

#parte1
python# Dados coletados manualmente em dois horários (manhã ~8h e tarde ~15h)

# Locais: Canteiro Arborizado (próx. Unicid), Terminal de Ônibus, Faculdade UNICID

# Fonte de referência IQA: CETESB (Companhia Ambiental do Estado de São Paulo)

# Faixas IQA (CETESB):

#   0–40   → Boa

#   41–80  → Moderada

#   81–120 → Ruim

#   121–200→ Muito Ruim

#   201–299→ Péssima



def classificar_iqa(iqa):

    match True:

        case _ if 0 <= iqa <= 40:

            return "Boa"

        case _ if 41 <= iqa <= 80:

            return "Moderada"

        case _ if 81 <= iqa <= 120:

            return "Ruim"

        case _ if 121 <= iqa <= 200:

            return "Muito Ruim"

        case _:

            return "Péssima"





def calcular_nota_conforto(temp, umidade, iqa):

    """

    Fórmula de Conforto Urbano (0 a 10):

    - Temperatura ideal: 22°C. Penaliza desvios.

    - Umidade ideal: entre 50% e 70%. Penaliza extremos.

    - IQA: quanto menor, melhor. Penaliza valores altos.

    """

    # Componente temperatura (0 a 4 pontos): penaliza desvio da zona de conforto

    desvio_temp = abs(temp - 22)

    nota_temp = max(0, 4 - (desvio_temp * 0.3))



    # Componente umidade (0 a 3 pontos): ideal entre 50% e 70%

    if 50 <= umidade <= 70:

        nota_umidade = 3

    elif umidade < 50:

        nota_umidade = max(0, 3 - ((50 - umidade) * 0.06))

    else:

        nota_umidade = max(0, 3 - ((umidade - 70) * 0.06))



    # Componente IQA (0 a 3 pontos): penaliza qualidade ruim do ar

    nota_iqa = max(0, 3 - (iqa * 0.025))



    nota_final = nota_temp + nota_umidade + nota_iqa

    return round(min(nota_final, 10), 2)





def analisar_microclima():

    # Estrutura: [Local, Horário, Temperatura (°C), Umidade (%), IQA]

    dados_locais = [

        ["Canteiro Arborizado", "Manhã (8h)",  24, 72, 32],

        ["Canteiro Arborizado", "Tarde (15h)", 28, 60, 38],

        ["Terminal de Ônibus",  "Manhã (8h)",  26, 65, 78],

        ["Terminal de Ônibus",  "Tarde (15h)", 31, 55, 92],

        ["Faculdade UNICID",    "Manhã (8h)",  25, 68, 45],

        ["Faculdade UNICID",    "Tarde (15h)", 30, 58, 61],

    ]



    metricas = ["Temperatura (°C)", "Umidade (%)", "IQA"]



    print("=" * 60)

    print("   ANÁLISE DE MICROCLIMA URBANO — ZONA LESTE SP")

    print("=" * 60)



    for registro in dados_locais:

        local, horario, temp, umidade, iqa = registro



        print(f"\n📍 Local: {local} | ⏰ Horário: {horario}")

        print("-" * 50)



        valores = [temp, umidade, iqa]

        for i, metrica in enumerate(metricas):

            print(f"   {metrica}: {valores[i]}")



        qualidade_ar = classificar_iqa(iqa)

        nota = calcular_nota_conforto(temp, umidade, iqa)



        print(f"   🌬️  Qualidade do Ar: {qualidade_ar}")

        print(f"   🏙️  Nota de Conforto Urbano: {nota} / 10")



        if nota >= 7:

            print("   ✅ Ambiente confortável para permanência prolongada.")

        elif nota >= 4:

            print("   ⚠️  Ambiente moderado. Atenção a grupos sensíveis.")

        else:

            print("   ❌ Ambiente desconfortável. Evite exposição prolongada.")



    print("\n" + "=" * 60)

    print("Análise concluída.")

    print("=" * 60)





analisar_microclima()

#parte2
python# Mapeamento físico real: Primeiro andar da UNICID

# Rota mapeada a partir da sala mais distante até as 3 saídas possíveis

# Nós do trajeto: Sala de Aula → Corredor Principal → Escada 1 → Escada 2 →

#                 Térreo (bifurcação) → Saída escolhida



import random

import time



def simular_evacuacao():

    # Lista dos nós do trajeto (do ponto inicial até a bifurcação)

    nos = [

        "Sala de Aula (Andar 1)",

        "Corredor Principal",

        "Topo da Escada 1",

        "Patamar intermediário",

        "Térreo — Ponto de Decisão",

    ]



    # Estado de cada nó (obstáculos ou facilitadores reais)

    estados = [

        "livre",          # Sala de Aula

        "fumaça leve",    # Corredor

        "livre",          # Topo da Escada 1

        "escada estreita — movimento lento",  # Patamar

        "bifurcação: 3 saídas disponíveis",   # Térreo

    ]



    # As 3 saídas da UNICID com seus estados

    saidas = [

        "Saída 1 — Rua lateral (salas ao lado, passagem direta)",

        "Saída 2 — Avenida principal (espaço amplo, mais segura)",

        "Saída 3 — Lanchonete (corredor apertado, saída pelos fundos)",

    ]



    estados_saidas = [

        "passagem direta para a rua, movimento moderado",

        "ampla, sinalizada, ponto de encontro na avenida",

        "corredor congestionado, mas com saída alternativa pelos fundos",

    ]



    # Inventário do agente

    inventario = ["crachá", "garrafa de água"]

    energia = 100

    posicao = 0

    evacuado = False



    print("=" * 60)

    print("   SIMULADOR DE EVACUAÇÃO — UNICID (1º ANDAR)")

    print("=" * 60)

    print(f"\n🚨 EMERGÊNCIA DETECTADA! Iniciando protocolo de evacuação.")

    print(f"👤 Agente iniciando do nó 0: {nos[0]}")

    print(f"🎒 Inventário: {inventario}")

    print(f"⚡ Energia: {energia}")

    print("-" * 60)



    # Loop principal: agente tenta avançar até chegar ao ponto de decisão

    while posicao < len(nos) and energia > 0 and not evacuado:

        local_atual = nos[posicao]

        estado_atual = estados[posicao]



        print(f"\n📍 Posição atual: [{posicao}] {local_atual}")

        print(f"   Estado: {estado_atual}")



        # Avaliação do nó atual com if aninhado

        if estado_atual == "livre":

            print("   ✅ Caminho livre. Avançando.")

            energia -= 10

            posicao += 1



        elif "fumaça" in estado_atual:

            print("   ⚠️  Há fumaça no corredor!")

            if "garrafa de água" in inventario:

                print("   💧 Usando garrafa de água para umedecer o pano. Atravessando com segurança.")

                inventario.remove("garrafa de água")

                energia -= 20

                posicao += 1

            else:

                print("   😰 Sem recurso para a fumaça. Agente recua um nó e busca rota alternativa.")

                energia -= 30

                if posicao > 0:

                    posicao -= 1



        elif "estreita" in estado_atual or "lento" in estado_atual:

            print("   🪜 Escada estreita — movimento mais lento, porém seguro.")

            energia -= 15

            posicao += 1



        elif "bifurcação" in estado_atual:

            # Chegou ao térreo — hora de escolher a saída

            print("\n" + "=" * 60)

            print("   🔀 PONTO DE DECISÃO: Térreo da UNICID")

            print("   O agente avalia as 3 saídas disponíveis:\n")



            melhor_saida = None

            melhor_score = -1



            for i, saida in enumerate(saidas):

                estado_saida = estados_saidas[i]

                print(f"   [{i+1}] {saida}")

                print(f"        → {estado_saida}")



                # Lógica de pontuação para escolha da melhor saída

                score = 0

                if "ampla" in estado_saida or "segura" in estado_saida:

                    score += 3

                if "direta" in estado_saida:

                    score += 2

                if "congestionado" in estado_saida or "apertado" in estado_saida:

                    score -= 1

                if "alternativa" in estado_saida:

                    score += 1



                print(f"        → Score de segurança calculado: {score}")



                if score > melhor_score:

                    melhor_score = score

                    melhor_saida = i



            print(f"\n   🧠 Agente decide pela: {saidas[melhor_saida]}")

            energia -= 10



            # Executa a saída escolhida

            estado_saida_escolhida = estados_saidas[melhor_saida]



            if "ampla" in estado_saida_escolhida or "segura" in estado_saida_escolhida:

                print("   ✅ Saída segura e organizada. Agente alcança a avenida!")

                evacuado = True



            elif "congestionado" in estado_saida_escolhida:

                print("   ⚠️  Corredor congestionado na lanchonete!")

                if energia > 20:

                    print("   💪 Agente tem energia suficiente para forçar passagem pelos fundos.")

                    energia -= 20

                    evacuado = True

                else:

                    print("   ❌ Energia insuficiente. Agente não consegue avançar pelos fundos.")

                    energia = 0



            else:

                print("   ✅ Passagem direta para a rua. Evacuação concluída pela saída lateral.")

                evacuado = True



            posicao += 1  # sai do loop principal



    # Resultado final

    print("\n" + "=" * 60)

    if evacuado:

        print("🏁 EVACUAÇÃO BEM-SUCEDIDA!")

        print(f"   Energia restante: {energia} / 100")

        print(f"   Inventário final: {inventario if inventario else 'vazio'}")

    elif energia <= 0:

        print("❌ FALHA NA EVACUAÇÃO.")

        print("   O agente ficou sem energia antes de alcançar a saída.")

    else:

        print("⚠️  Simulação encerrada sem conclusão definida.")

    print("=" * 60)





simular_evacuacao()

"""PARTE 3: Reflexão Crítica

Parágrafo 1: Durante o mapeamento físico da UNICID, percebi algo que raramente acontece quando simplesmente caminhamos por um espaço: fui obrigado a parar, observar e nomear cada elemento do ambiente com precisão. O corredor que todo dia atravesso distraidamente se transformou em um "nó" com um "estado", a escada ganhou atributos como "estreita" e "lenta", e as três saídas do campus deixaram de ser apenas portões e passaram a ser variáveis com pesos e condições lógicas. Esse exercício revelou que o ato de programar não começa na tela — ele começa no olhar. Antes de digitar uma linha de código, eu precisei desenvolver uma leitura analítica do espaço físico, o que me fez perceber o quanto a nossa percepção cotidiana é superficial e automatizada.

Parágrafo 2: Ao tentar transformar portas e corredores em variáveis lógicas, o maior desafio foi lidar com a ambiguidade da realidade. No mundo físico, uma saída "apertada" é uma impressão subjetiva; no código, ela precisa virar uma penalidade numérica no score de decisão, ou uma condição booleana que ativa ou bloqueia um caminho. Essa tradução forçada me ensinou que toda situação complexa, seja ela uma rota de fuga ou um problema pessoal, pode ser decomposta em partes menores e avaliadas por critérios explícitos. O if/else aninhado que o agente usa para decidir entre as saídas nada mais é do que uma formalização do raciocínio que qualquer pessoa faz em situação de emergência — só que, ao programar, somos obrigados a tornar esse raciocínio visível, ordenado e sem contradições. É impossível deixar uma condição "mais ou menos" resolvida: o computador exige clareza absoluta onde nossa mente frequentemente aceita a ambiguidade.

Parágrafo 3: Isso me fez refletir que, no meu dia a dia, aprender a programar está mudando a forma como enfrento problemas que aparentemente não têm nenhuma relação com tecnologia. Quando preciso tomar uma decisão difícil — escolher entre prioridades, gerenciar tempo ou resolver um conflito — começo a enxergar a situação como um algoritmo: quais são as entradas disponíveis? Quais são as condições que alteram o resultado? Existe um loop que estou repetindo sem perceber, e como posso quebrá-lo? A lógica de programação não é apenas uma ferramenta técnica; ela é um modo de pensar que valoriza a decomposição de problemas, a identificação de estados e a tomada de decisão baseada em critérios explícitos. Aprender a programar, portanto, não me tornou apenas alguém que escreve código — me tornou alguém que lê a realidade de forma mais estruturada, paciente e estratégica
"""