# -*- coding: utf-8 -*-
"""SISTEMA_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyC2srnoQLOv8oibuk4C8cgRIwgUrWWR
"""

#desafio1
def processar_vendas():
    total_compra = 0.0
    itens_comprados = 0

    quantidade_tipos = int(input("Quantos produtos diferentes foram comprados? "))

    for i in range(1, quantidade_tipos + 1):
        nome = input("Nome do produto: ")
        preco = float(input("Preço unitário: "))
        qtd = int(input("Quantidade deste produto: "))

        if preco <= 0 or qtd <= 0:
            print(f"Erro: Valores inválidos para {nome}")
        else:
            subtotal = preco * qtd
            total_compra += subtotal
            itens_comprados += qtd

    if total_compra > 500.00:
        total_final = total_compra * 0.90
        print("Desconto de 10% aplicado!")
    elif total_compra > 200.00:
        total_final = total_compra * 0.95
    else:
        total_final = total_compra

    print(f"Resumo: {itens_comprados} itens. Total a pagar: R$ {total_final:.2f}")

#desafio2
def analisar_clima():
    soma_temperaturas = 0.0
    dias_quentes = 0
    alerta_extremo = False

    for dia in range(1, 7 + 1):
        temp = float(input(f"Digite a temperatura do dia {dia}: "))
        soma_temperaturas += temp

        if temp > 35.0:
            dias_quentes += 1

        if temp > 45.0 or temp < -5.0:
            alerta_extremo = True

    media = soma_temperaturas / 7

    print(f"Média semanal: {media:.2f}")
    print(f"Dias acima de 35°C: {dias_quentes}")

    if alerta_extremo:
        print("CUIDADO: Condições climáticas perigosas detectadas!")
    else:
        print("Clima dentro da normalidade operacional.")

#desafio3
def sistema_notas_turma():
    total_alunos = int(input("Quantos alunos existem na turma? "))

    for j in range(1, total_alunos + 1):
        aluno_nome = input("Nome do aluno: ")
        n1 = float(input("Nota 1: "))
        n2 = float(input("Nota 2: "))

        media_aluno = (n1 + n2) / 2

        if media_aluno >= 7.0:
            print(f"{aluno_nome}: Aprovado com média {media_aluno:.2f}")
        elif media_aluno >= 5.0:
            print(f"{aluno_nome}: Recuperação (Média: {media_aluno:.2f})")
        else:
            print(f"{aluno_nome}: Reprovado")

#desafio4
def simulador_poupanca():
    saldo = float(input("Valor inicial do investimento: "))
    taxa = float(input("Taxa de juros mensal (em %): "))
    meses = int(input("Número de meses da simulação: "))

    for m in range(1, meses + 1):
        aporte = float(input(f"Quanto deseja depositar no mês {m}? (0 para nenhum) "))

        saldo += aporte
        juros = saldo * (taxa / 100)
        saldo += juros

        print(f"Mês {m}: Saldo atualizado = R$ {saldo:.2f}")

        if saldo > 10000.0:
            print(f"Parabéns! Você atingiu a meta de 10k no mês {m}")

    print(f"Resultado final após {meses} meses: R$ {saldo:.2f}")

"""RESPOSTAS – QUESTÕES DE REFLEXÃO

Sobre Tipagem:
No Python, a função input() sempre retorna uma string. Se você não usar int() ou float(), os valores não serão numéricos. Isso pode causar erros em operações matemáticas ou resultados incorretos, como concatenação de texto em vez de soma. Por exemplo, "2" + "2" resulta em "22" e não em 4. Portanto, é necessário converter os valores usando int() ou float() antes de fazer cálculos.

Sobre Estruturas (range):
Para contar de 1 até N incluindo o N, usamos:

for i in range(1, N + 1):

Isso acontece porque o Python inclui o valor inicial, mas exclui o valor final no range(). Por exemplo, range(1, 5) gera 1, 2, 3, 4. Diferente do pseudocódigo, que normalmente inclui o último valor, no Python precisamos usar +1 para garantir que o limite final seja alcançado.
"""