# -*- coding: utf-8 -*-
"""projeto-o-algoritmo-de-auditoria-de-dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKI_UorKdE1IFNg-x0nsDnv2ERyTn9Bk
"""

# -*- coding: utf-8 -*-
"""auditoria_de_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyRwW_R7CVc7EfUaiMU34rly8VubCijR
"""

print("="*60)

print("Seja bem-vindo ao sistema de auditoria de vendas semanais!")

LIMITE_DE_SEGURANCA = 10000

# valor das 3 venda

V1 = float(input("Valor da venda 1: "))
V2 = float(input("Valor da venda 2: "))
V3 = float(input("Valor da venda 3: "))

#função q faz media das vendas e dai imprime PRONTO

def analisar_vendas():

 global LIMITE_DE_SEGURANCA
 media = (V1+V2+V3) / 3
 print(f"A média das vendas é: {media}")
 return media

media_das_vendas = analisar_vendas()

# média mais alta que limite de segurança PRONTO

resposta_valida = ("s", "n")
legitimo = input("A venda é legitima? (s/n) ").lower().strip()

while legitimo not in resposta_valida:
 print("Resposta invalida.")
 legitimo = input("A venda é legitima? (s/n)").lower().strip()

if legitimo == "s":
 print("Sucesso!")
elif legitimo == "n":
 LIMITE_DE_SEGURANCA = float(input("Qual deve ser o novo valor do limite de segurança? "))
 print(f"Sucesso! o novo valor do limite de segurança é R${LIMITE_DE_SEGURANCA}")

else:
 print("entrada nao reconhecida")

if legitimo == "n" and media_das_vendas >= LIMITE_DE_SEGURANCA:
 print("SISTEMA EM QUARENTENA")
else:
 print("MÉDIA DAS VENDAS NORMAL")
# se QUALQUER venda for x5 maior (ou mais) que a media_das_vendas, mensagem REVISÃO MANUAL

if V1 >= media_das_vendas * 5 or V2 >= media_das_vendas * 5 or V3 >= media_das_vendas * 5:
  print("REVISÃO MANUAL")

print("="*60)

# type de todas as variavel

print(f"Tipo de variável de V1: {type(V1)}")
print(f"Tipo de variável de V2: {type(V2)}")
print(f"Tipo de variável de V3: {type(V3)}")
print(f"Tipo de variável de media_das_vendas: {type(media_das_vendas)}")
print(f"Tipo de variável de LIMITE_DE_SEGURANCA: {type(LIMITE_DE_SEGURANCA)}")
print(f"Tipo de variável de V1: {type(V1)}")

print("="*60)